### ISSUE TITLE
Address open questions surrounding max body

### ISSUE THREAD

**Issue by mdb** [akamai-open/AkamaiOPEN-edgegrid-node#5]
Per conversation [here](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/issues/10), there are some open questions surrounding the max body size requirements of Akamai's REST API.

The Akamai documentation continues to read that "The size of the POST body must be less than or equal to the value specified by the service. Any request that does not meet this criteria SHOULD be rejected during the signing process, as the request will be rejected by EdgeGrid," though @maglietti pointed out [this is incorrect and should be updated](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/issues/10#issuecomment-126341800).

Could Akamai please update the documentation such that AkamaiOPEN-edgegrid-node be refactored accordingly, assuming changes are necessary?

Thanks!

**Comment by ktyacke** [comment]
@mdb I'll pick up the ball on this one and see what we can do about getting the docs updated. Sorry for any confusion it may have caused.

**Comment by mdb** [comment]
NP - Thank you! I'll stay posted.

**Comment by ktyacke** [comment]
Hey @mdb Can review the following and let me know if it helps to clarify things for you? Would like to get feedback prior to updating our docs. Thanks!

If the POST body is smaller than the amount specified by the max_body header, the entire body will be signed by the server and the signatures will match. However, if the POST body is larger than the amount specified by the max_body header, only the bytes specified by max_body will be signed. Therefore the signed portion of the POST body must match the amount that is passed by the max_body header.

*Example:* 
Body size: 560
max_body: 2048
Total amount of the body signed: 560

and

Body size: 3024
max_body: 2048
Total amount of the body signed: 2048

**Comment by mdb** [comment]
@ktyacke Thanks for the fast followup!

I confess, I'm still a bit confused. Is `max_body` a response header present on certain Akamai API responses? I may have overlooked it, but I'm not aware of any documentation pertaining to such a header.

**Comment by ktyacke** [comment]
Hey @mdb , 
The max-body property in the .edgerc file defines the maximum amount of body data that can be signed for the given API. The default value should be 131072 bytes (128K), unless otherwise specified in the documentation for a specific API. The Edgegrid Client should read and respect the number defined by the max-body property of the section of the .edgerc file that is being read, and default to 131072 bytes if none is found.

As to the documentation mentioning that the client should reject any requests where the size of the POST body does not match the max-body, this is incorrect and will be updated. The client should sign the amount of the POST body that is defined by the max-body or default to 131072 bytes. The server will then validate the signature using the value it has defined for the expected amount of the body which should be signed and return a signature mis-match error if the values do not match. 

I hope this helps to clarify things!

**Comment by mdb** [comment]
Yes - that clarifies! I was initially distracted by "header."

Thanks!

**Comment by ktyacke** [comment]
As was I when initially discussing the topic. I will be personally updating the docs to help clarify this issue. Thanks for brining it to our attention!

**Comment by stevemcginnis** [comment]
My pull request implements this with the exception of changing the default.
When I merge I will make that change too
